version: '3'

services:
  weather_histogram:
    build:
      context: ./weather_histogram/
      dockerfile: Dockerfile
    ports:
      - ${WEATHER_APP_PUBLISHED_PORT}:8050
    env_file:
      - ./.env
    environment:
      - LAUNCHED_FROM_DOCKER_COMPOSE=1
    restart: always

volumes:
  weather_histogram_volume:
